export const GET_CURR_TODO_DATA = 'GET_CURR_TODO_DATA'

export const REORDER_TODOS = 'REORDER_TODOS'

export const HIGHLIGHT_TODO = 'HIGHLIGHT_TODO'


export const MARK_ONE_TODO_IS_COMPLETE = 'MARK_ONE_TODO_IS_COMPLETE'


export const TOGGLE_APP_NEW_ADD_TODO_MODE = 'TOGGLE_APP_NEW_ADD_TODO_MODE'

export const TOGGLE_APP_EDITING_TODO_MODE = 'TOGGLE_APP_EDITING_TODO_MODE'

export const UPDATE_TODO = 'UPDATE_TODO'

export const ADD_TODO = 'ADD_TODO'