const SAGA_GET_INIT_TODO_DATA = 'SAGA_GET_INIT_TODO_DATA'
const SAGA_REORDER_TODOS = 'SAGA_REORDER_TODOS'
const SAGA_HIGHLIGHT_TODO = 'SAGA_HIGHLIGHT_TODO'

const SAGA_MARK_ONE_TODO_IS_COMPLETE = 'SAGA_MARK_ONE_TODO_IS_COMPLETE'

const SAGA_TOGGLE_APP_NEW_ADD_TODO_MODE = 'SAGA_TOGGLE_APP_NEW_ADD_TODO_MODE'
const SAGA_TOGGLE_APP_EDITING_TODO_MODE = 'SAGA_TOGGLE_APP_EDITING_TODO_MODE'
const SAGA_UPDATE_TODO = 'SAGA_UPDATE_TODO'
const SAGA_ADD_TODO = 'SAGA_ADD_TODO'
const SAGA_CHANGE_APP_CURR_TAB_MODE =  'SAGA_CHANGE_APP_CURR_TAB_MODE'

const SAGA = {
  SAGA_GET_INIT_TODO_DATA,
  SAGA_REORDER_TODOS,
  SAGA_HIGHLIGHT_TODO,
  SAGA_MARK_ONE_TODO_IS_COMPLETE,
  SAGA_TOGGLE_APP_NEW_ADD_TODO_MODE,
  SAGA_TOGGLE_APP_EDITING_TODO_MODE,
  SAGA_UPDATE_TODO,
  SAGA_ADD_TODO,
  SAGA_CHANGE_APP_CURR_TAB_MODE,
}

export default SAGA