const GET_INIT_TODO_DATA = 'GET_INIT_TODO_DATA'

const REORDER_TODOS = 'REORDER_TODOS'

const HIGHLIGHT_TODO = 'HIGHLIGHT_TODO'


const MARK_ONE_TODO_IS_COMPLETE = 'MARK_ONE_TODO_IS_COMPLETE'


const TOGGLE_APP_NEW_ADD_TODO_MODE = 'TOGGLE_APP_NEW_ADD_TODO_MODE'

const TOGGLE_APP_EDITING_TODO_MODE = 'TOGGLE_APP_EDITING_TODO_MODE'

const UPDATE_TODO = 'UPDATE_TODO'

const ADD_TODO = 'ADD_TODO'

const CHANGE_APP_CURR_TAB_MODE =  'CHANGE_APP_CURR_TAB_MODE'


const StoreActionType = {
  GET_INIT_TODO_DATA,
  REORDER_TODOS,
  HIGHLIGHT_TODO,
  MARK_ONE_TODO_IS_COMPLETE,
  TOGGLE_APP_NEW_ADD_TODO_MODE,
  TOGGLE_APP_EDITING_TODO_MODE,
  UPDATE_TODO,
  ADD_TODO,
  CHANGE_APP_CURR_TAB_MODE,
}

export default StoreActionType